### ISSUE TITLE
Double free of register mapping

### ISSUE THREAD

**Issue by BugraEryilmaz** [parsa-epfl/flexus#51]
Description
Assertion failure for freeing a register mapping that is already unmapped.

Steps to Reproduce
Run the timing model with the 1c_stress.

Expected Behavior
The register should not be freed if it is not mapped already.

Actual Behavior
```
245275 <cycle.cpp:1465> {28670487249}- 000-uarch FinalCommit:#374[00]  {clsComputation}  QEMU disas: cmp x2, #0 {raised}	{retired}
245276 <Effects.cpp:154> {28670487249}- CPU[00]#374 MapEffect free mapping for pCCpd(cc-Bits[0])
245277 <registers.cpp:75> (<undefined>[<undefined>]) {28670487249}- Assertion failed: (!(status != kUnmapped)) :  aRegister=cc-Bits[0] status=Unmapped
```

Comments
It can be related to renaming PSTATE because cmp instruction modifies the PSTATE for the NZCV bits.

**Comment by branylagaffe** [comment]
Is fixed by commit bfa60febdbfcecf712b36caab7fb2e946e85431e
