### ISSUE TITLE
Add TLB entry for 'bad' pagefault

### ISSUE THREAD

**Issue by BugraEryilmaz** [parsa-epfl/flexus#77]
### Description
Speculative branch redirection creates a large number of page faults. These faults take a long time to resolve and block the CPU's front end.

### Expected Behavior
The faults should not block the progress of CPU.

### Actual Behavior
Progress is blocked so much that watchdog exception is triggered.

### Additional Information
- Version/Branch: next -- maintainer/bryan

### Possible solutions
1. Have a TLB entry for faulty addresses and early return for all addresses that will result in page fault.
2. Clear the frontend when branch redirection is complete

**Comment by BugraEryilmaz** [comment]
Taken solution 1 with this commit: 4660af95ff058e28e0018da08c93ee1088ce7b62

**Comment by branylagaffe** [comment]
Merged here: 1bb962d981f4a9fa78ad7ae897c1bebcb0074b5b
