### ISSUE TITLE
TLB process ID

### ISSUE THREAD

**Issue by BugraEryilmaz** [parsa-epfl/flexus#78]
**As a** user of flexus,
**I want** TLB to keep track of process id 
**So that** When we run multiple applications in the same machine we do not have TLB related issues.

**Specification:**
1. [Condition 1: TLB should keep track of process id
   - [Detail 1] While inserting a translation, it should also insert a variable for process id
   - [Detail 2] It should read the current process id from system registers
   - [Detail 3] While checking if an address can be translated using TLB, it should also check process id

2. [Condition 2: TLB should also work with global translations that are not bond to a specific application

**Tasks:**
- [Task 1: implementing the process id feature in the TLB

---

**UPDATE**
-[22.10.2024]:  implemented with 763578c0661e5e9b7213f7f39fb34c5131e9a0c3

**Comment by branylagaffe** [comment]
Merged here -> 6e600805ccb08ed37d0fc9abb1e3bb148686e651
