### ISSUE TITLE
2nd Level TLB

### ISSUE THREAD

**Issue by BugraEryilmaz** [parsa-epfl/flexus#79]
**As a** use of flexus,
**I want** a 2 level TLB hierarchy
**So that** we can model modern CPU architectures.

**Specification:**
1. [Condition 1: Before a page walk. it should check the second level TLB (sTLB) for the given address
   - [Detail 1] With a given delay, the cycle accurate simulator should check a second level TLB for address translation
   - [Detail 2] If the address is also not in the sTLB, then it should go for the page walk

2. [Condition 2: After a page walk, it should insert the address into sTLB for future access

**Tasks:**
- [Task 1: implement sTLB in flexus

---

**UPDATE**
-[22.10.2024]:  implemented with dc96928f98d210ab3e1586fe92b37a0649983b36 and fffaa7295daca4dbf715a7a84bb840d07e575c65

**Comment by branylagaffe** [comment]
Merged here -> 4352e2b361b1c442a867dfc0f897847010677de4
